-- 코드를 입력하세요
SELECT CAR.CAR_ID, CAR.CAR_TYPE, 
        ROUND(DAILY_FEE * 30 * (1 - DISCOUNT_RATE * 0.01),0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR CAR JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY HISTORY 
        ON CAR.CAR_ID = HISTORY.CAR_ID JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN PLAN
        ON CAR.CAR_TYPE = PLAN.CAR_TYPE
WHERE CAR.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE END_DATE > '2022-11-01' AND START_DATE < '2022-12-01') 
    AND PLAN.DURATION_TYPE='30일 이상'
GROUP BY CAR.CAR_ID
HAVING FEE >=500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR.CAR_TYPE ASC, CAR.CAR_ID DESC
        