-- 코드를 입력하세요
SELECT BOOK.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(PRICE * SALES) AS TOTAL_SALES
FROM BOOK JOIN AUTHOR ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID JOIN BOOK_SALES BS ON BOOK.BOOK_ID = BS.BOOK_ID
WHERE SALES_DATE <= DATE('2022-01-31')
GROUP BY BOOK.AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC 