# -- 코드를 입력하세요
# SELECT *,
# CAR_ID,
# if(start_date < '2022-10-16' and end_date > '2022-10-17','대여중', '대여가능') as AVAILABILITY
# from CAR_RENTAL_COMPANY_RENTAL_HISTORY
# GROUP BY CAR_ID
# #WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE
# ORDER BY CAR_ID DESC

# SELECT DISTINCT CAR_ID, 
# IF(CAR_ID IN (SELECT DISTINCT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE), '대여중', '대여 가능') AS AVAILABILTIY 
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
# ORDER BY CAR_ID DESC
SELECT DISTINCT CAR_ID,
IF(CAR_ID IN (SELECT DISTINCT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE), '대여중', '대여 가능') AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
ORDER BY CAR_ID DESC