-- 코드를 입력하세요
SELECT FO.PRODUCT_ID, FP.PRODUCT_NAME, SUM(PRICE*AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT FP JOIN FOOD_ORDER FO ON FP.PRODUCT_ID = FO.PRODUCT_ID
WHERE FO.PRODUCE_DATE LIKE '2022-05%'
GROUP BY FO.PRODUCT_ID 
ORDER BY TOTAL_SALES DESC, FO.PRODUCT_ID ASC
