-- 코드를 입력하세요
SELECT APNT_NO, PT.PT_NAME, APP.PT_NO, APP.MCDP_CD,DOC.DR_NAME, APP. APNT_YMD 
FROM PATIENT PT RIGHT JOIN APPOINTMENT APP ON PT.PT_NO = APP.PT_NO
                LEFT JOIN DOCTOR DOC ON APP.MDDR_ID = DOC.DR_ID
WHERE APNT_CNCL_YN LIKE 'N' AND APP.MCDP_CD LIKE 'CS'  
                            AND APNT_YMD LIKE '2022-04-13%'
ORDER BY APP.APNT_YMD
