-- 코드를 입력하세요
SELECT RC.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR RC JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY RH ON RC.CAR_ID =     RH.CAR_ID
WHERE RC.CAR_TYPE = '세단' AND RH.START_DATE LIKE '2022-10%'
GROUP BY CAR_ID
ORDER BY CAR_ID DESC